apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hk-api-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hk-api-gateway
    spec:
      containers:
      - name: demo
        image: localhub.predic8.de/hk-api-gateway:$BUILD_NUMBER
        ports:
        - containerPort: 8765
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /info
            port: 8765
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /info
            port: 8765
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 5
        imagePullPolicy: Always
      imagePullSecrets:
        - name: p8-localhub-credentials
