eureka:
  client:
    serviceUrl:
      defaultZone: http://${HK_SERVICE_REGISTRY_SERVICE_HOST}:${HK_SERVICE_REGISTRY_SERVICE_PORT}/eureka/
zuul:
  routes: 
    talk-service: 
      path: /talk-service/**
    speaker-service:
      path: /speaker-service/**
server:
  port: 8765